//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAspNETv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactSupport
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<int> marchandId { get; set; }
    
        public virtual Proprietaire Proprietaire { get; set; }
    }
}
