//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAspNETv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Historiques = new HashSet<Historique>();
            this.Images = new HashSet<Image>();
            this.Vues = new HashSet<Vue>();
        }
    
        public int Id { get; set; }
        public string description_ { get; set; }
        public Nullable<decimal> price { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public string status { get; set; }
        public Nullable<bool> livrable { get; set; }
        public Nullable<bool> garantee { get; set; }
        public Nullable<int> promoId { get; set; }
        public Nullable<int> propreitaireId { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historique> Historiques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vue> Vues { get; set; }
    }
}
