//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAspNETv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.Produits = new HashSet<Produit>();
        }
    
        public int Id { get; set; }

        [StringLength(256, ErrorMessage = "le nom de la promotion doit avoir au minimum 3 lettres", MinimumLength = 3)]
        [Display(Name = "Description")]
        [Required(ErrorMessage = "la description est obligatoire")]
        public string Name { get; set; }

        [Range(1, 99, ErrorMessage = "le prix doit etre entre 1 et 99 ")]
        [Required(ErrorMessage = "le pourcentage est obligatoire")]
        public Nullable<int> Pourcentage { get; set; }

        [Display(Name = "Date de fin de validite")]
        [Required(ErrorMessage = "cette date est obligatoire")]
        public Nullable<System.DateTime> Date_Validite { get; set; }
        public Nullable<System.DateTime> Date_Creation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit> Produits { get; set; }
    }
}
